{
 "title": "Load Management Workshop",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy downstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix!=\"admin\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining requests before CB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_rq",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_rq",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request based CB open",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_open",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_rq_open",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining connections before CB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_cx",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_cx\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection based CB open",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_cx_open",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_cx_open\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining retries before CB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_remaining_retries",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_remaining_retries",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry based CB open",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_retry_open",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_high_rq_retry_open",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Downstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP requests - default priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (code)(rate(http_requests_made_total{priority=\"default\"}[1m]))"
    }
   ]
  },
  {
   "title": "HTTP requests - high priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (code)(rate(http_requests_made_total{priority=\"high\"}[1m]))"
    }
   ]
  },
  {
   "title": "Upstreams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP requests in",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "rate(http_requests_in_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "gRPC Requests In",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "rate(grpc_requests_in_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP requests completed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(http_requests_completed_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "gRPC requests completed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "rate(grpc_requests_completed_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}