{
 "title": "Load Management Workshop",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy downstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix!=\"admin\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy ratelimit OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rate(envoy_ratelimit_ok[10s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Envoy ratelimit over limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(envoy_ratelimit_over_limit[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy ratelimit errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(envoy_ratelimit_error[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy ratelimit cluster healthy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "envoy_cluster_membership_healthy{envoy_cluster_name=\"some_ratelimit_service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Downstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "gRPC requests made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(grpc_requests_made_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Upstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "gRPC Requests In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(grpc_requests_in_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}