{
 "title": "Load Management Workshop",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy downstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix!=\"admin\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy active downstream CX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy rejected downstream connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(envoy_listener_downstream_global_cx_overflow[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Downstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP requests made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(http_requests_made_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC requests made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(grpc_requests_made_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Upstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "HTTP requests in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(http_requests_in_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Requests In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(grpc_requests_in_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}