{
 "title": "Load Management Workshop",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy downstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix!=\"admin\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limit enabled ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(envoy_http_local_rate_limit_enabled[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limit enforced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(envoy_http_local_rate_limit_enforced[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limit OK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(envoy_http_local_rate_limit_ok[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate limited requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(envoy_http_local_rate_limit_rate_limited[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Downstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HTTP requests made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(http_requests_made_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Upstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "HTTP requests in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(http_requests_in_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}