global:
  scrape_interval: 5s
scrape_configs:
 - job_name: upstream
   dns_sd_configs:
     - names:
       - 'upstream'
       type: 'A'
       port: 9092
 - job_name: downstream
   dns_sd_configs:
     - names:
       - 'downstream'
       type: 'A'
       port: 9094
 - job_name: envoy
   metrics_path: /stats/prometheus
   dns_sd_configs:
     - names:
       - 'envoy'
       type: 'A'
       port: 9901