services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    ports:
      - "9901:9901"
      - "9902:9902"
      - "9903:9903"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
  upstream:
    build: 
      context: ../code/upstream
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
      - "9093:9093"
  downstream:
    build: 
      context: ../code/downstream
      dockerfile: Dockerfile
    ports:
      - "9094:9094"