services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    ports:
      - "9901:9901"
      - "9902:9902"
      - "9903:9903"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
      - 6071:6071
    depends_on:
      - redis
    volumes:
      - ./ratelimit/config:/data/ratelimit/config
    environment:
      - USE_STATSD=false
      - USE_PROMETHEUS=true
      - PROMETHEUS_ADDR=:6071
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=${CONFIG_TYPE:-FILE}

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./provisioning:/etc/grafana/provisioning"
      - "./dashboards:/etc/grafana/dashboards"
  upstream:
    build: 
      context: ../../code/upstream
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
      - "9093:9093"
  downstream:
    build: 
      context: ../../code/downstream
      dockerfile: Dockerfile
    ports:
      - "9094:9094"
  auth:
    build: 
      context: ../../code/auth
      dockerfile: Dockerfile

volumes:
  grafana_storage: {}