{
 "title": "Load Management Workshop",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Adaptive Concurrency Sample RTT Msecs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_sample_rtt_msecs",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Upstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy downstream requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix!=\"admin\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adaptive Concurrency Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_concurrency_limit",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adaptive Concurrency Gradient",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_gradient",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Adaptive Concurrency MinRTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_min_rtt_msecs",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Downstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "HTTP requests made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(http_requests_made_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC requests made",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(grpc_requests_made_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Upstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "HTTP requests in",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(http_requests_in_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Requests In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(grpc_requests_in_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(http_requests_completed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC requests completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(grpc_requests_completed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}